languageCode = "en-us"
title = "Kine's Art"
baseurl = "http://example.org/"
theme = "prologue"

[params]
  name = "Kristine Linnea"
  description = "Traditional Artist"
  maintainerURL = "https://bredley.co.uk/"
  maintainer = "Bradley Garrod"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kristinelinneahl/"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/Unicornowlkine"


[[params.social]]
  medium = "twitch"
  icon = "twitch"
  link = "https://twitch.tv/unicornowl"


# Portfolio column one

[[params.portfolio1]]
  title = "\"Lord of the Rings\" - Acrylic - 2020"
  alt = "A painting of Gandalf and Frodo overlooking Rivendell."
  source = "img/lotr.jpg"
  id = "lotr"
  size = "A3"
  medium = "Acrylic"
  year = "2020"

[[params.portfolio1]]
  title = "\"Brother Bear\" - Guoache - 2018"
  alt = "A painting of Koda and Kenai looking at the Northern Lights."
  source = "img/brotherbear.jpg"
  id = "bb"
  size = "35.5cm &times; 25cm"
  medium = "Guoache"
  year = "2018"

# Portfolio column two

[[params.portfolio2]]
  title = "\"Happy Panda\" - Acrylic - 2020"
  alt = "A painting of a Panda eating bamboo."
  source = "img/panda.jpg"
  id = "panda"
  size = "A3"
  medium = "Acrylic"
  year = "2020"

#[[params.portfolio2]]
#  title = "Natoque Vitae"
#  alt = ""
#  source = "img/pic05.jpg"
#  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "\"Alpine Lake\" - Acrylic - 2018"
  alt = ""
  source = "img/alpinelake.jpg"
  id = "alpineLake"
  size = "35.5cm &times; 25cm"
  medium = "Acrylic"
  year = "2018"
