languageCode = "en-us"
title = "Kine's Art"
baseurl = "http://example.org/"
theme = "prologue"

[params]
  name = "Kristine Linnea"
  description = "Traditional Artist"
  maintainerURL = "https://bredley.co.uk/"
  maintainer = "Bradley Garrod"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kristinelinneahl/"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/Unicornowlkine"


[[params.social]]
  medium = "twitch"
  icon = "twitch"
  link = "https://twitch.tv/unicornowl"


# Portfolio column one

[[params.portfolio1]]
  title = "Lord of the Rings"
  alt = ""
  source = "img/lotr.jpg"
  url = ""
  id = "img1"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"
  id = "img2"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
