languageCode = "en"
defaultcontentlanguage = "en"
title = "Kine's Art"
baseurl = "https://kinesart.com"
canonifyURLs = true

# New renderer - needed to make inline HTML work
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
  name = "Kristine Linnea"
  description = "Traditional Artist"
  maintainerURL = "https://bredley.co.uk/"
  maintainer = "Bradley Garrod"
  imagefolder = "img"
  tourfolder = "img/tour-of-norway"
  mapboxkey = ""
  currency = "£"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/playlist?list=PLV_HbQSACXpI99Yhv0-ir8zz0L89Q8eEK"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kinesart/"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/Unicornowlkine"


[[params.social]]
  medium = "twitch"
  icon = "twitch"
  link = "https://twitch.tv/unicornowl"


# Portfolio column one

[[params.portfolio1]]
  name = "Lord of the Rings"
  alt = "A painting of Gandalf and Frodo overlooking Rivendell."
  filename = "lotr"
  id = "lotr"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio1]]
  name = "Minnie"
  alt = "My boyfriend's dog gazing into the distance."
  filename = "minnie"
  id = "minnie"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio1]]
  name = "Magical Mushroom"
  alt = "A painting of a mushroom in a forest."
  filename = "magical-mushroom"
  id = "magicalMushroom"
  size = "13cm &times; 20.5cm"
  medium = "Gouache"
  year = "2020"
  main = true

[[params.portfolio1]]
  name = "Brother Bear"
  alt = "A painting of Koda and Kenai looking at the Northern Lights."
  filename = "brother-bear"
  id = "brotherBear"
  size = "35.5cm &times; 25cm"
  medium = "Gouache"
  year = "2018"
  main = false

[[params.portfolio1]]
  name = "Evening Stroll"
  alt = "A painting of Koda and Kenai looking at the Northern Lights."
  filename = "evening-stroll"
  id = "eveningStroll"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2020"
  main = false

[[params.portfolio1]]
  name = "Evening Breeze"
  alt = "A painting of a Dutch coastline, featuring a windmill."
  filename = "evening-breeze"
  id = "eveningBreeze"
  size = "30Cm &times; 30cm"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio1]]
  name = "Peeking Mountain"
  alt = "A mountain top peeking through the trees."
  filename = "peeking-mountain"
  id = "peekingMountain"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2020"

[[params.portfolio1]]
  name = "Tropical Gaze"
  alt = "A painting of a mountain top peaking through the trees."
  filename = "tropical-gaze"
  id = "tropicalGaze"
  size = "20.5cm &times; 13cm"
  medium = "Watercolour"
  year = "2016"
  main = false

[[params.portfolio1]]
  name = "Misty Mountains"
  alt = "A painting of a sunset with big clouds and distant mountains."
  filename = "misty-mountains"
  id = "mistyMountains"
  size = "17cm &times; 25.5cm"
  medium = "Gouache"
  year = "2020"
  main = true

[[params.portfolio1]]
  name = "Sunny Days"
  alt = "A painting of an Australian beach with palm trees."
  filename = "sunny-days"
  id = "sunnyDays"
  size = "13cm &times; 20.5cm"
  medium = "Gouache"
  year = "2020"
  main = false


# Portfolio column two

[[params.portfolio2]]
  name = "Northern Nights"
  alt = "A Norwegian cabin on a winter night, surrounded by mountains, with the northern lights above."
  filename = "northern-nights"
  id = "northernNights"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio2]]
  name = "Happy Panda"
  alt = "A painting of a Panda eating bamboo."
  filename = "happy-panda"
  id = "panda"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio2]]
  name = "Hidden Falls"
  alt = "A hidden waterfall surrounded by mossy mountains."
  filename = "hidden-falls"
  id = "hiddenFalls"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2020"
  main = false

[[params.portfolio2]]
  name = "Lightly Dusted"
  alt = "A painting pinecone lightly dusted with snow."
  filename = "lightly-dusted"
  id = "lightlyDusted"
  size = "A4"
  medium = "Watercolour"
  year = "2017"
  main = true

[[params.portfolio2]]
  name = "Let Light Overcome"
  alt = "A painting of the 'Let Light Overcome' album cover, by 'Our Last Night'."
  filename = "oln-wolf"
  id = "olnWolf"
  size = "15cm &times; 15cm"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio2]]
  name = "Scar"
  alt = "A painting of Scar from The Lion King."
  filename = "scar"
  id = "scar"
  size = "A3"
  medium = "Acrylic"
  year = "2019"
  main = false

[[params.portfolio2]]
  name = "Handsome Jack"
  alt = "A painting of Handsome Jack from the Borderlands series."
  filename = "handsome-jack"
  id = "handsomeJack"
  size = "A3"
  medium = "Acrylic"
  year = "2019"
  main = false

[[params.portfolio2]]
  name = "Lonely Boat"
  alt = "A painting sail boat."
  filename = "lonely-boat"
  id = "lonelyBoat"
  size = "A4"
  medium = "Acrylic"
  year = "2018"
  main = false

[[params.portfolio2]]
  name = "Kraken's Cave"
  alt = "A painting of a Kraken in a cave."
  filename = "krakens-cave"
  id = "krakensCave"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio2]]
  name = "Cotton Candy Clouds"
  alt = "A painting of clouds that resemble cotton candy."
  filename = "cotton-candy-clouds"
  id = "cottonCandyClouds"
  size = "17.5cm &times; 25.5cm"
  medium = "Gouache"
  year = "2020"
  main = false


# Portfolio column 3

[[params.portfolio3]]
  name = "Neuschwanstein"
  alt = "A painting of the Neuschwanstein castle, with a sunset in the background."
  filename = "neuschwanstein"
  id = "neuschwanstein"
  size = "35.5cm &times; 25cm"
  medium = "Acrylic"
  year = "2018"
  main = true

[[params.portfolio3]]
  name = "Bonfire Evening"
  alt = "A cosy bonfire in the woods during a late autumn afternoon."
  filename = "bonfire-evening"
  id = "bonfireEvening"
  size = "13cm &times; 20.5cm"
  medium = "Gouache"
  year = "2020"
  main = true

[[params.portfolio3]]
  name = "Forest Walk"
  alt = "A painting of a path leading into the woods."
  filename = "forest-walk"
  id = "forestWalk"
  size = "13cm &times; 20.5cm"
  medium = "Acrylic"
  year = "2020"
  main = false

[[params.portfolio3]]
  name = "Alpine Lake"
  alt = "A painting of Alpine Lake."
  filename = "alpine-lake"
  id = "alpineLake"
  size = "35.5cm &times; 25cm"
  medium = "Acrylic"
  year = "2018"
  main = false

[[params.portfolio3]]
  name = "Autumn Afternoon"
  alt = "A painting of an autumn scene with a river running through the middle."
  filename = "autumn-afternoon"
  id = "autumnAfternoon"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2019"
  main = true

[[params.portfolio3]]
  name = "Strutting Stallion"
  alt = "A painting of a horse in a field."
  filename = "strutting-stallion"
  id = "struttingStallion"
  size = "A3"
  medium = "Acrylic"
  year = "2020"
  main = false

[[params.portfolio3]]
  name = "Sculpture"
  alt = "A pencil sketch of a sculpture."
  filename = "sculpture"
  id = "sculpture"
  size = "A2"
  medium = "Pencil"
  year = "2017"
  main = false

[[params.portfolio3]]
  name = "A Pinch of Springtime"
  alt = "A miniature painting of Bob Ross' \"Hint of Springtime\""
  filename = "pinch-of-springtime"
  id = "springtime"
  size = "9cm &times; 7cm"
  medium = "Acrylic"
  year = "2018"
  main = true

[[params.portfolio3]]
  name = "Palm Dreams"
  alt = "A painting of a palm tree on a beach after sunset."
  filename = "palm-dreams"
  id = "palmDreams"
  size = "20.5cm &times; 13cm"
  medium = "Acrylic"
  year = "2020"
  main = true

[[params.portfolio3]]
  name = "Soft Skies"
  alt = "A painting of whispy clouds at sunset."
  filename = "soft-skies"
  id = "softSkies"
  size = "20.5cm &times; 17.5cm"
  medium = "Gouache"
  year = "2020"
  main = false


# Paintings for sale

[[params.sale1]]
  name = "Misty Mountains"
  alt = "A painting of a sunset with big clouds and distant mountains."
  filename = "misty-mountains"
  id = "mistyMountains"
  size = "17cm &times; 25.5cm"
  medium = "Gouache"
  year = "2020"
  price = "65.00"

[[params.sale2]]
  name = "Soft Skies"
  alt = "A painting of whispy clouds at sunset."
  filename = "soft-skies"
  id = "softSkies"
  size = "20.5cm &times; 17.5cm"
  medium = "Gouache"
  year = "2020"
  price = "60.00"

[[params.sale3]]
  name = "Cotton Candy Clouds"
  alt = "A painting of clouds that resemble cotton candy."
  filename = "cotton-candy-clouds"
  id = "cottonCandyClouds"
  size = "17.5cm &times; 25.5cm"
  medium = "Gouache"
  year = "2020"
  price = "60.00"


# Norway Tour Markers

[[ params.marker ]]
  id = "bokeskogen"
  location = "Bøkeskogen, Larvik"
  medium = "Gouache"
  size = "20.5cm &times; 18.5cm"
  filename = "bokeskogen"
  x = 59.0571
  y = 10.0260
