languageCode = "en"
defaultcontentlanguage = "en"
title = "Kine's Art"
baseurl = "https://kinesart.com"
theme = "prologue"
canonifyURLs = true

[params]
  name = "Kristine Linnea"
  description = "Traditional Artist"
  maintainerURL = "https://bredley.co.uk/"
  maintainer = "Bradley Garrod"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/playlist?list=PLV_HbQSACXpI99Yhv0-ir8zz0L89Q8eEK"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kinesart/"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/Unicornowlkine"


[[params.social]]
  medium = "twitch"
  icon = "twitch"
  link = "https://twitch.tv/unicornowl"


# Portfolio column one

[[params.portfolio1]]
  name = "Lord of the Rings"
  alt = "A painting of Gandalf and Frodo overlooking Rivendell."
  source = "img/lotr.jpg"
  id = "lotr"
  size = "A3"
  medium = "Acrylic"
  year = "2020"

[[params.portfolio1]]
  name = "Brother Bear"
  alt = "A painting of Koda and Kenai looking at the Northern Lights."
  source = "img/brotherbear.jpg"
  id = "brotherBear"
  size = "35.5cm &times; 25cm"
  medium = "Gouache"
  year = "2018"

[[params.portfolio1]]
  name = "Evening Stroll"
  alt = "A painting of Koda and Kenai looking at the Northern Lights."
  source = "img/evening-stroll.jpg"
  id = "eveningStroll"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2020"

[[params.portfolio1]]
  name = "Evening Breeze"
  alt = "A painting of a Dutch coastline, featuring a windmill."
  source = "img/evening-breeze.jpg"
  id = "eveningBreeze"
  size = "30Cm &times; 30cm"
  medium = "Acrylic"
  year = "2020"

[[params.portfolio1]]
  name = "Peeking Mountain"
  alt = "A mountain top peeking through the trees."
  source = "img/peeking-mountain.jpg"
  id = "peekingMountain"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2020"

[[params.portfolio1]]
  name = "Tropical Gaze"
  alt = "A mountain top peaking through the trees."
  source = "img/tropical-gaze.jpg"
  id = "tropicalGaze"
  size = "20.5cm &times; 13cm"
  medium = "Watercolour"
  year = "2016"


# Portfolio column two

[[params.portfolio2]]
  name = "Happy Panda"
  alt = "A painting of a Panda eating bamboo."
  source = "img/panda.jpg"
  id = "panda"
  size = "A3"
  medium = "Acrylic"
  year = "2020"

[[params.portfolio2]]
  name = "Lightly Dusted"
  alt = "A painting pinecone lightly dusted with snow."
  source = "img/lightly-dusted.jpg"
  id = "lightlyDusted"
  size = "A4"
  medium = "Watercolour"
  year = "2017"

[[params.portfolio2]]
  name = "Scar"
  alt = "A painting of Scar from The Lion King."
  source = "img/scar.jpg"
  id = "scar"
  size = "A3"
  medium = "Acrylic"
  year = "2019"

[[params.portfolio2]]
  name = "Handsome Jack"
  alt = "A painting of Handsome Jack from the Borderlands series."
  source = "img/handsome-jack.jpg"
  id = "handsomeJack"
  size = "A3"
  medium = "Acrylic"
  year = "2019"

[[params.portfolio2]]
  name = "Lonely Boat"
  alt = "A painting sail boat."
  source = "img/lonely-boat.jpg"
  id = "lonelyBoat"
  size = "A4"
  medium = "Acrylic"
  year = "2018"


# Portfolio column 3

[[params.portfolio3]]
  name = "Neuschwanstein"
  alt = "A painting of the Neuschwanstein castle, with a sunset in the background."
  source = "img/neuschwanstein.jpg"
  id = "neuschwanstein"
  size = "35.5cm &times; 25cm"
  medium = "Acrylic"
  year = "2018"

[[params.portfolio3]]
  name = "Alpine Lake"
  alt = "A painting of Alpine Lake."
  source = "img/alpinelake.jpg"
  id = "alpineLake"
  size = "35.5cm &times; 25cm"
  medium = "Acrylic"
  year = "2018"

[[params.portfolio3]]
  name = "Autumn Afternoon"
  alt = "A painting of an autumn scene with a river running through the middle."
  source = "img/autumn-afternoon.jpg"
  id = "autumnAfternoon"
  size = "20.5cm &times; 13cm"
  medium = "Gouache"
  year = "2019"

[[params.portfolio3]]
  name = "Strutting Stallion"
  alt = "A painting of a horse in a field."
  source = "img/strutting-stallion.jpg"
  id = "struttingStallion"
  size = "A3"
  medium = "Acrylic"
  year = "2020"

[[params.portfolio3]]
  name = "Sculpture"
  alt = "A pencil sketch of a sculpture."
  source = "img/sculpture.jpg"
  id = "sculpture"
  size = "A2"
  medium = "Pencil"
  year = "2017"

[[params.portfolio3]]
  name = "A Pinch of Springtime"
  alt = "A miniature painting of Bob Ross' \"Hint of Springtime\""
  source = "img/pinch-of-springtime.jpg"
  id = "springtime"
  size = "9cm &times; 7cm"
  medium = "Acrylic"
  year = "2018"
